### ISSUE TITLE
Error: Forbidden

### ISSUE THREAD

**Issue by luienvar-zz** [dolcalmi/nequi-node#1]
`
  { Error: Forbidden
      ....
      type: 'NequiAPIError',
      rawType: undefined,
      code: undefined,
      param: undefined,
      message: 'Forbidden',
      detail: undefined,
      raw: undefined,
      headers: undefined,
      requestId: '94c259c0-fba5-11e7-9c6e-0540fba27540',
      statusCode: undefined }
`

Eso pasa cuando intento generar un codigo Qr con el siguiente comando(valores son de ejemplo):

`  
    const nequiClient = nequi(accessKey, secretKey, apiKey)
    const res = await nequiClient.qrPayments.create({
      phoneNumber: '3009871234',
      value: '100'
    })
`

**Comment by dolcalmi** [comment]
@luienvar desafortunadamente nequi aun tiene problemas con la estandarización del API y con la estabilidad del ambiente de pruebas. Si lees en la documentación https://docs.conecta.nequi.com.co/?api=qrPayments#!/Pagos32QR/post_services_paymentservice_generatecodeqr dice lo siguiente:

- **phoneNumber (string**): NIT del comercio o identificador de la terminal, caja o dependencia que va a realizar un cobro ,
- **value (string)**: Valor a cobrar

de acuerdo a esto deberias usar el nit registrado con ellos y no un número de teléfono.

ps: hice las pruebas con mis credenciales y no recibí un forbidden si no un 11-9L (El phoneNumber, code o transactionId no existen), pero me ha pasado y depende de ciertas horas del dia (incluso los fines de semana siempre hay muchos problemas para probar)
